language: ruby
cache:
  - bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile

deploy:
  provider: heroku
  api_key:
    secure: Rails.application.credentials.dig('production', 'heroku', 'api_key')
  app: telestrations
  on:
    repo: joe11000/telestrations

script: bundle exec rspec -t ~no_travis
