language: ruby
rvm: 2.5.1


deploy:
  provider: heroku
  api_key: <%= Rails.application.credentials[Rails.env.to_sym][:heroku][:api_key] %>
  run:
    - "rake db:create"
    - "rake db:migrate"
    - restart
    - "rake cleanup"

