development:
  adapter: async

test:
  adapter: async
  # adapter: redis
  # url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://h:p0edc7e2bfce1dd97fedfdc264364fd4f4c2f113922601069ef8a0b4731840bfd@ec2-100-24-145-65.compute-1.amazonaws.com:9309

