development:
  adapter: async

test:
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(Rails.env.to_sym, :heroku, :redis_url) %>
  channel_prefix: telestrations_production
