development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(Rails.env.to_sym, :heroku, :redis_url) %>
  channel_prefix: telestrations_production
