development:
  adapter: async

test:
  adapter: async
  # adapter: redis
  # url: redis://localhost:6379/1

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:production, :redis, :url) %>
  host: 'ec2-18-204-150-188.compute-1.amazonaws.com'
  port: '7509'
  password: <%= Rails.application.credentials.dig(:production, :redis, :password) %>
