development:
  adapter: async

test:
  adapter: async
  # adapter: redis
  # url: redis://localhost:6379/1

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:production, :heroku, :redis_url) %>
  channel_prefix: telestrations_production
