# This was all uncommented...I am commenting it out to try and remove dropbox
# production:
#   app_key: <%= ENV['DROPBOX_APP_KEY'] %>
#   app_secret: <%= ENV['DROPBOX_APP_SECRET'] %>
#   access_token: <%= ENV['DROPBOX_ACCESS_TOKEN'] %>
#   access_token_secret: <%= ENV['DROPBOX_ACCESS_TOKEN_SECRET'] %>
#   user_id: <%= ENV['DROPBOX_USER_ID'] %>
#   access_type: <%= ENV['DROPBOX_ACCESS_TYPE'] %>

# development:
#   app_key: <%= ENV['DROPBOX_APP_KEY'] %>
#   app_secret: <%= ENV['DROPBOX_APP_SECRET'] %>
#   access_token: <%= ENV['DROPBOX_ACCESS_TOKEN'] %>
#   access_token_secret: <%= ENV['DROPBOX_ACCESS_TOKEN_SECRET'] %>
#   user_id: <%= ENV['DROPBOX_USER_ID'] %>
#   access_type: <%= ENV['DROPBOX_ACCESS_TYPE'] %>
