production: &production
  adapter: redis
  url: redis://dev.telestrations.herokuapp.com:6381
development: &development
  adapter: redis
  url: redis://dev.telestrations.herokuapp.com:28080
test: *development


local: &local
  :url: redis://dev.telestrations.herokuapp.com:6379
  :host: dev.telestrations.herokuapp.com
  :port: 6379
  :timeout: 1
  :inline: true
development: *local
test: *local
